### ISSUE TITLE
Doesn't work with very small numbers

### ISSUE THREAD

**Issue by kevin-west-10x** [dfkaye/safe-math#1]
Using a value like "0.0000000000186264514923095703125" seems to break in the expand function, specifically on line 448 when replacing commas it converts the string to the number 1.862645149230957e-11, and then checks mantissa length by counting chars after the decimal. This is obviously now incorrect due to the scientific notation.

**Comment by dfkaye** [comment]
Thanks for catching that, @kevin-west-10x - I’ll add some tests for it a bit later this week - unless you want to give it a shot?

**Comment by dfkaye** [comment]
@kevin-west-10x  -- Rather quick and dirty fix is up.

If you want, you can view the suite running on my blog at https://dfkaye.com/demos/safe-math-test-suite/ - look for the "very small numbers in scientific notation" test.

Thanks again :)

**Comment by dfkaye** [comment]
P.S. Feel free to re-open this issue if you find similar issues regarding scientific notation and/or very small numeric values.

**Comment by kevin-west-10x** [comment]
Thanks!
